### PR TITLE
add core.battery provider

### PR DESCRIPTION
**Pull request by soycode**
Similar to Firefox - some tests seem broken but unrelated, still I'll do a bit of a sanity check before cutting a release.

### CODE REVIEW

**Comment by soycode** [comment]
Turns out that Chrome apps aggressively reject synchronous XHR, which unfortunately was the change needed in freedom-proper to get the tests passing in Chrome-the-browser again. https://github.com/freedomjs/freedom/commit/899fb41c3681de1d7abb29a5100228b18496d4e5

Going synchronous was a step backwards, but loading multiple APIs from the same manifest was timing out in Chrome otherwise. A really hacky fix would be to add some logic such that the XHR is async unless it's Chrome-the-browser-and-not-app. I may try that for now, but any other thoughts are welcome.

**Comment by soycode** [comment]
And I did that - https://github.com/freedomjs/freedom/pull/323

This fixes most of the tests (in that it actually runs them), the remaining few failing have been flaky regardless I believe.

**Comment by soycode** [comment]
Alright, it's down to the one failing test that has been habitually failing (some ambiguity back w/main freedom, not a blocker) - `X integration: storage.isolated.json clears the store`

So, if it looks good to you I'm up for merging/cutting a release.

**Comment by bemasc** [comment]
OK, :+1:

**Pull request merged**
